# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target '01-AVFondaton_OverView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 01-AVFondaton_OverView
pod 'AFNetworking', '~> 3.0'

end
